### ISSUE TITLE
Problems with boot

### ISSUE THREAD

**Issue by loralighte** [Potabi/PCLI#1]
![image](https://user-images.githubusercontent.com/62919224/172976787-3cd980ac-daa2-4d67-b85f-4ca0bfabcddd.png)
It's nice that it boots but this is still problematic. Not sure why it's so upset about having to use gzip-6 when the ISO handles it just fine. Typo maybe? Will look into it further. I will also see on using a different compression algorithm.

Lastly there is the issue of it not booting correctly, which I assume to be an issue based on the compression algorithm issue, but I will look around to see what I may have done wrong.

**Comment by loralighte** [comment]
![image](https://user-images.githubusercontent.com/62919224/173092123-45abbc91-16e9-4463-95f0-025f2e8e2534.png)
Progress update, fixed the boot issue and it now boots to this. Going to look into what I did wrong and how to fix it

**Comment by ghost** [comment]
I usually fix this by adding a label with `gpart modify -i index -l label geom` and making sure the correct mounting points are under `/etc/fstab` for a gpt lable the path would look like `/dev/gpt/label-here` for example in the `/etc/fstab`.

**Comment by loralighte** [comment]
Adding a label should work. I could have a manual `/etc/fstab` generator in the build script with some default values.

**Comment by loralighte** [comment]
I was looking through the codebase to see if there was anything I missed and yes, the issue is I forgot I needed to generate the /dev/fstab file

**Comment by loralighte** [comment]
I added the FSTAB and did a test, did not change a thing:
https://github.com/Potabi/PCLI/blob/45a052cdc049460dff26d175acd30ce424c6359a/build.new.sh#L73-L77

**Comment by loralighte** [comment]
Looking at the error message some more, and I think I see the issue with my current setup

**Comment by loralighte** [comment]
I tested to see if we can load zroot, but I couldn't. The zroot is where I have all the source.

**Comment by loralighte** [comment]
@time-killer-games Could you perhaps look into the code some more, I can't seem to figure out the issue.

![image](https://user-images.githubusercontent.com/62919224/173202309-0d2880ce-5a5c-4d7e-bf38-562fafa9856c.png)

if you can figure out what I am doing wrong here, that'd be awesome.

**Comment by loralighte** [comment]
![image](https://user-images.githubusercontent.com/62919224/173208713-66ce9e1d-c0c2-4994-94ce-7c229a20cf31.png)
Uh huh... Yes. I think I found the issue :)

**Comment by loralighte** [comment]
![image](https://user-images.githubusercontent.com/62919224/173209025-42ddb840-b855-44ac-873c-bc4e4b355211.png)
Hell yeah, progress

**Comment by loralighte** [comment]
![image](https://user-images.githubusercontent.com/62919224/173209359-289b781a-a092-4e0f-8fe4-fd3fca247cdc.png)
Uh it paused here, and I think that's that. We have a basic installer tool >.>

**Comment by loralighte** [comment]
![image](https://user-images.githubusercontent.com/62919224/173209399-0b4a4cb2-8947-4fbe-afbf-71bbac046340.png)
